// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	stdsql "database/sql"
	"fmt"
	"sync"

	"entgo.io/ent/dialect"
)

// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
	config
	// APIKey is the client for interacting with the APIKey builders.
	APIKey *APIKeyClient
	// Account is the client for interacting with the Account builders.
	Account *AccountClient
	// AccountGroup is the client for interacting with the AccountGroup builders.
	AccountGroup *AccountGroupClient
	// Announcement is the client for interacting with the Announcement builders.
	Announcement *AnnouncementClient
	// AnnouncementRead is the client for interacting with the AnnouncementRead builders.
	AnnouncementRead *AnnouncementReadClient
	// AuthIdentity is the client for interacting with the AuthIdentity builders.
	AuthIdentity *AuthIdentityClient
	// AuthIdentityChannel is the client for interacting with the AuthIdentityChannel builders.
	AuthIdentityChannel *AuthIdentityChannelClient
	// BatchImageEvent is the client for interacting with the BatchImageEvent builders.
	BatchImageEvent *BatchImageEventClient
	// BatchImageItem is the client for interacting with the BatchImageItem builders.
	BatchImageItem *BatchImageItemClient
	// BatchImageJob is the client for interacting with the BatchImageJob builders.
	BatchImageJob *BatchImageJobClient
	// ChannelMonitor is the client for interacting with the ChannelMonitor builders.
	ChannelMonitor *ChannelMonitorClient
	// ChannelMonitorDailyRollup is the client for interacting with the ChannelMonitorDailyRollup builders.
	ChannelMonitorDailyRollup *ChannelMonitorDailyRollupClient
	// ChannelMonitorHistory is the client for interacting with the ChannelMonitorHistory builders.
	ChannelMonitorHistory *ChannelMonitorHistoryClient
	// ChannelMonitorRequestTemplate is the client for interacting with the ChannelMonitorRequestTemplate builders.
	ChannelMonitorRequestTemplate *ChannelMonitorRequestTemplateClient
	// CompositeModelRoute is the client for interacting with the CompositeModelRoute builders.
	CompositeModelRoute *CompositeModelRouteClient
	// ErrorPassthroughRule is the client for interacting with the ErrorPassthroughRule builders.
	ErrorPassthroughRule *ErrorPassthroughRuleClient
	// Group is the client for interacting with the Group builders.
	Group *GroupClient
	// IdempotencyRecord is the client for interacting with the IdempotencyRecord builders.
	IdempotencyRecord *IdempotencyRecordClient
	// IdentityAdoptionDecision is the client for interacting with the IdentityAdoptionDecision builders.
	IdentityAdoptionDecision *IdentityAdoptionDecisionClient
	// PaymentAuditLog is the client for interacting with the PaymentAuditLog builders.
	PaymentAuditLog *PaymentAuditLogClient
	// PaymentOrder is the client for interacting with the PaymentOrder builders.
	PaymentOrder *PaymentOrderClient
	// PaymentProviderInstance is the client for interacting with the PaymentProviderInstance builders.
	PaymentProviderInstance *PaymentProviderInstanceClient
	// PendingAuthSession is the client for interacting with the PendingAuthSession builders.
	PendingAuthSession *PendingAuthSessionClient
	// PromoCode is the client for interacting with the PromoCode builders.
	PromoCode *PromoCodeClient
	// PromoCodeUsage is the client for interacting with the PromoCodeUsage builders.
	PromoCodeUsage *PromoCodeUsageClient
	// Proxy is the client for interacting with the Proxy builders.
	Proxy *ProxyClient
	// RedeemCode is the client for interacting with the RedeemCode builders.
	RedeemCode *RedeemCodeClient
	// SecuritySecret is the client for interacting with the SecuritySecret builders.
	SecuritySecret *SecuritySecretClient
	// Setting is the client for interacting with the Setting builders.
	Setting *SettingClient
	// SubscriptionPlan is the client for interacting with the SubscriptionPlan builders.
	SubscriptionPlan *SubscriptionPlanClient
	// TLSFingerprintProfile is the client for interacting with the TLSFingerprintProfile builders.
	TLSFingerprintProfile *TLSFingerprintProfileClient
	// UsageCleanupTask is the client for interacting with the UsageCleanupTask builders.
	UsageCleanupTask *UsageCleanupTaskClient
	// UsageLog is the client for interacting with the UsageLog builders.
	UsageLog *UsageLogClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserAllowedGroup is the client for interacting with the UserAllowedGroup builders.
	UserAllowedGroup *UserAllowedGroupClient
	// UserAttributeDefinition is the client for interacting with the UserAttributeDefinition builders.
	UserAttributeDefinition *UserAttributeDefinitionClient
	// UserAttributeValue is the client for interacting with the UserAttributeValue builders.
	UserAttributeValue *UserAttributeValueClient
	// UserPlatformQuota is the client for interacting with the UserPlatformQuota builders.
	UserPlatformQuota *UserPlatformQuotaClient
	// UserSubscription is the client for interacting with the UserSubscription builders.
	UserSubscription *UserSubscriptionClient

	// lazily loaded.
	client     *Client
	clientOnce sync.Once
	// ctx lives for the life of the transaction. It is
	// the same context used by the underlying connection.
	ctx context.Context
}

type (
	// Committer is the interface that wraps the Commit method.
	Committer interface {
		Commit(context.Context, *Tx) error
	}

	// The CommitFunc type is an adapter to allow the use of ordinary
	// function as a Committer. If f is a function with the appropriate
	// signature, CommitFunc(f) is a Committer that calls f.
	CommitFunc func(context.Context, *Tx) error

	// CommitHook defines the "commit middleware". A function that gets a Committer
	// and returns a Committer. For example:
	//
	//	hook := func(next ent.Committer) ent.Committer {
	//		return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Commit(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	CommitHook func(Committer) Committer
)

// Commit calls f(ctx, m).
func (f CommitFunc) Commit(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Commit commits the transaction.
func (tx *Tx) Commit() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Committer = CommitFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Commit()
	})
	txDriver.mu.Lock()
	hooks := append([]CommitHook(nil), txDriver.onCommit...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Commit(tx.ctx, tx)
}

// OnCommit adds a hook to call on commit.
func (tx *Tx) OnCommit(f CommitHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onCommit = append(txDriver.onCommit, f)
	txDriver.mu.Unlock()
}

type (
	// Rollbacker is the interface that wraps the Rollback method.
	Rollbacker interface {
		Rollback(context.Context, *Tx) error
	}

	// The RollbackFunc type is an adapter to allow the use of ordinary
	// function as a Rollbacker. If f is a function with the appropriate
	// signature, RollbackFunc(f) is a Rollbacker that calls f.
	RollbackFunc func(context.Context, *Tx) error

	// RollbackHook defines the "rollback middleware". A function that gets a Rollbacker
	// and returns a Rollbacker. For example:
	//
	//	hook := func(next ent.Rollbacker) ent.Rollbacker {
	//		return ent.RollbackFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Rollback(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	RollbackHook func(Rollbacker) Rollbacker
)

// Rollback calls f(ctx, m).
func (f RollbackFunc) Rollback(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Rollback rollbacks the transaction.
func (tx *Tx) Rollback() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Rollbacker = RollbackFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Rollback()
	})
	txDriver.mu.Lock()
	hooks := append([]RollbackHook(nil), txDriver.onRollback...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Rollback(tx.ctx, tx)
}

// OnRollback adds a hook to call on rollback.
func (tx *Tx) OnRollback(f RollbackHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onRollback = append(txDriver.onRollback, f)
	txDriver.mu.Unlock()
}

// Client returns a Client that binds to current transaction.
func (tx *Tx) Client() *Client {
	tx.clientOnce.Do(func() {
		tx.client = &Client{config: tx.config}
		tx.client.init()
	})
	return tx.client
}

func (tx *Tx) init() {
	tx.APIKey = NewAPIKeyClient(tx.config)
	tx.Account = NewAccountClient(tx.config)
	tx.AccountGroup = NewAccountGroupClient(tx.config)
	tx.Announcement = NewAnnouncementClient(tx.config)
	tx.AnnouncementRead = NewAnnouncementReadClient(tx.config)
	tx.AuthIdentity = NewAuthIdentityClient(tx.config)
	tx.AuthIdentityChannel = NewAuthIdentityChannelClient(tx.config)
	tx.BatchImageEvent = NewBatchImageEventClient(tx.config)
	tx.BatchImageItem = NewBatchImageItemClient(tx.config)
	tx.BatchImageJob = NewBatchImageJobClient(tx.config)
	tx.ChannelMonitor = NewChannelMonitorClient(tx.config)
	tx.ChannelMonitorDailyRollup = NewChannelMonitorDailyRollupClient(tx.config)
	tx.ChannelMonitorHistory = NewChannelMonitorHistoryClient(tx.config)
	tx.ChannelMonitorRequestTemplate = NewChannelMonitorRequestTemplateClient(tx.config)
	tx.CompositeModelRoute = NewCompositeModelRouteClient(tx.config)
	tx.ErrorPassthroughRule = NewErrorPassthroughRuleClient(tx.config)
	tx.Group = NewGroupClient(tx.config)
	tx.IdempotencyRecord = NewIdempotencyRecordClient(tx.config)
	tx.IdentityAdoptionDecision = NewIdentityAdoptionDecisionClient(tx.config)
	tx.PaymentAuditLog = NewPaymentAuditLogClient(tx.config)
	tx.PaymentOrder = NewPaymentOrderClient(tx.config)
	tx.PaymentProviderInstance = NewPaymentProviderInstanceClient(tx.config)
	tx.PendingAuthSession = NewPendingAuthSessionClient(tx.config)
	tx.PromoCode = NewPromoCodeClient(tx.config)
	tx.PromoCodeUsage = NewPromoCodeUsageClient(tx.config)
	tx.Proxy = NewProxyClient(tx.config)
	tx.RedeemCode = NewRedeemCodeClient(tx.config)
	tx.SecuritySecret = NewSecuritySecretClient(tx.config)
	tx.Setting = NewSettingClient(tx.config)
	tx.SubscriptionPlan = NewSubscriptionPlanClient(tx.config)
	tx.TLSFingerprintProfile = NewTLSFingerprintProfileClient(tx.config)
	tx.UsageCleanupTask = NewUsageCleanupTaskClient(tx.config)
	tx.UsageLog = NewUsageLogClient(tx.config)
	tx.User = NewUserClient(tx.config)
	tx.UserAllowedGroup = NewUserAllowedGroupClient(tx.config)
	tx.UserAttributeDefinition = NewUserAttributeDefinitionClient(tx.config)
	tx.UserAttributeValue = NewUserAttributeValueClient(tx.config)
	tx.UserPlatformQuota = NewUserPlatformQuotaClient(tx.config)
	tx.UserSubscription = NewUserSubscriptionClient(tx.config)
}

// txDriver wraps the given dialect.Tx with a nop dialect.Driver implementation.
// The idea is to support transactions without adding any extra code to the builders.
// When a builder calls to driver.Tx(), it gets the same dialect.Tx instance.
// Commit and Rollback are nop for the internal builders and the user must call one
// of them in order to commit or rollback the transaction.
//
// If a closed transaction is embedded in one of the generated entities, and the entity
// applies a query, for example: APIKey.QueryXXX(), the query will be executed
// through the driver which created this transaction.
//
// Note that txDriver is not goroutine safe.
type txDriver struct {
	// the driver we started the transaction from.
	drv dialect.Driver
	// tx is the underlying transaction.
	tx dialect.Tx
	// completion hooks.
	mu         sync.Mutex
	onCommit   []CommitHook
	onRollback []RollbackHook
}

// newTx creates a new transactional driver.
func newTx(ctx context.Context, drv dialect.Driver) (*txDriver, error) {
	tx, err := drv.Tx(ctx)
	if err != nil {
		return nil, err
	}
	return &txDriver{tx: tx, drv: drv}, nil
}

// Tx returns the transaction wrapper (txDriver) to avoid Commit or Rollback calls
// from the internal builders. Should be called only by the internal builders.
func (tx *txDriver) Tx(context.Context) (dialect.Tx, error) { return tx, nil }

// Dialect returns the dialect of the driver we started the transaction from.
func (tx *txDriver) Dialect() string { return tx.drv.Dialect() }

// Close is a nop close.
func (*txDriver) Close() error { return nil }

// Commit is a nop commit for the internal builders.
// User must call `Tx.Commit` in order to commit the transaction.
func (*txDriver) Commit() error { return nil }

// Rollback is a nop rollback for the internal builders.
// User must call `Tx.Rollback` in order to rollback the transaction.
func (*txDriver) Rollback() error { return nil }

// Exec calls tx.Exec.
func (tx *txDriver) Exec(ctx context.Context, query string, args, v any) error {
	return tx.tx.Exec(ctx, query, args, v)
}

// Query calls tx.Query.
func (tx *txDriver) Query(ctx context.Context, query string, args, v any) error {
	return tx.tx.Query(ctx, query, args, v)
}

var _ dialect.Driver = (*txDriver)(nil)

// ExecContext allows calling the underlying ExecContext method of the transaction if it is supported by it.
// See, database/sql#Tx.ExecContext for more information.
func (tx *txDriver) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := tx.tx.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Tx.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the transaction if it is supported by it.
// See, database/sql#Tx.QueryContext for more information.
func (tx *txDriver) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := tx.tx.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Tx.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
